CREATE TABLE user (
  id INT AUTO_INCREMENT,
  name CHAR(30) NOT NULL UNIQUE,
  password CHAR(30) NOT NULL,
  balance INT NOT NULL DEFAULT 5000,
  score INT NOT NULL DEFAULT 0,
  PRIMARY KEY(id)
);

CREATE TABLE message (
	id INT AUTO_INCREMENT,
	userId INT NOT NULL,
	publishTime TIMESTAMP NOT NULL DEFAULT NOW(),
	digest CHAR(40) NOT NULL,
	content TEXT NOT NULL,
	opened BOOL DEFAULT FALSE,
	PRIMARY KEY(id)
);

CREATE TABLE usertask (
	id INT AUTO_INCREMENT,
	userId INT NOT NULL,
	task BLOB NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE expense (
	id INT AUTO_INCREMENT,
	userTaskId INT NOT NULL,
	amount INT NOT NULL,
	PRIMARY KEY(id)
);
